"""Build Laker Quest's campus tile map from OpenStreetMap data.

Usage:
    python3 tools/osm_to_map.py <map.osm> [--campus-image allendale_campus_map.jpg] [--preview out.png]

<map.osm> is an OpenStreetMap XML export (openstreetmap.org -> Export) that
covers the Allendale campus. Buildings, roads, footpaths, parking, water,
woods, fields and the golf course are drawn into tiles of TILE_M meters and
written to src/campus_map.js, one row per line.

--campus-image is GVSU's campus map image (the A-F / 1-9 grid version). When
given, parking lots get their permit colors from it, and the converter fits
the transform from that image's pixels to tiles, so signs, NPCs and enemy
areas written in image coordinates (campus.js, data.js) land in the right
places.
"""
import json
import math
import os
import re
import sys
import xml.etree.ElementTree as ET

from PIL import Image, ImageDraw

# Area to include (degrees) and tile size (meters).
NORTH, SOUTH = 42.9745, 42.9500
WEST, EAST = -85.9135, -85.8735
TILE_M = 9.0
SUPER = 4   # supersampling for polygon coverage
STAND_DEPTH = 3   # tiles of bleachers along each side of a stadium field

LAT0 = (NORTH + SOUTH) / 2
M_PER_DEG_LAT = 111_132.0
M_PER_DEG_LON = 111_320.0 * math.cos(math.radians(LAT0))
W = int(round((EAST - WEST) * M_PER_DEG_LON / TILE_M))
H = int(round((NORTH - SOUTH) * M_PER_DEG_LAT / TILE_M))

# Building name (OSM) -> game id. These ids are what interiors, map labels
# and dialogue refer to; other buildings get an id made from their name.
GAME_IDS = [
    (r'Frey Living', 'flc'), (r'Kleiner', 'klc'), (r'Kirkhof', 'kc'),
    (r'Mary Idema Pew Library', 'lib'), (r'Zumberge Hall', 'jhz'), (r'^Fieldhouse$', 'fh'),
    (r'Padnos', 'pad'), (r'Alumni House', 'ah'), (r'Au Sable', 'ash'),
    (r'Kindschi', 'khs'), (r'Performing Arts', 'pac'), (r'Cook-Dewitt', 'cdc'),
    (r'Kelly Family', 'ktb'), (r'Ravine Center', 'rac'), (r'Central Utilit', 'cub'),
    (r'^Service Building', 'ser'), (r'Seidman House', 'sh'), (r'Recreation Center', 'rc'),
]

# Image pixel positions of buildings on GVSU's campus map, used to line the
# map image up with OSM. (Same label points the image tracer uses.)
IMAGE_LABELS = [
    ('Kirkhof', 375, 352), ('Mary Idema Pew Library', 349, 348), ('Zumberge Hall', 416, 352),
    ('Au Sable', 450, 341), ('Lake Huron', 455, 360), ('Seidman House', 445, 374),
    ('Lake Superior', 422, 377), ('Performing Arts', 394, 379), ('Lake Michigan Hall', 432, 397),
    ('Lake Ontario', 456, 397), ('Calder Residence', 510, 381), ('Calder Fine Arts', 516, 400),
    ('Cook-Dewitt', 392, 328), ('Henry Hall', 386, 293), ('Loutit', 389, 283),
    ('Padnos', 404, 278), ('Kindschi', 363, 261), ('Marketplace', 351, 276),
    ('Mackinac Hall', 417, 236), ('Manitou', 411, 247), ('Kelly Family', 283, 217),
    ('Alumni House', 347, 98), ('Ravine Center', 311, 151), ('Central Utilit', 419, 93),
    ('Kleiner', 452, 159), ('Copeland', 443, 196), ('Robinson', 451, 218),
    ('Holton-Hooker', 461, 247), ('VanSteeland', 411, 484), ('South Apartment C', 381, 556),
    ('South Apartment D', 399, 571), ('Campus Health', 340, 520), ('Art Gallery Support', 340, 529),
    ('Children', 261, 350), ('Blue Connection', 381, 447), ('Swanson', 529, 200),
    ('Kistler', 459, 186), ('Pickard', 480, 196), ('Johnson Living', 432, 170),
]

HEADER = """// GENERATED by tools/osm_to_map.py from OpenStreetMap data
// (c) OpenStreetMap contributors, ODbL: https://www.openstreetmap.org/copyright
// Safe to edit by hand: change a character in `rows` to change that tile.
//
// Tile legend:
//   .  grass                  B  building (shapes come from connected B tiles)
//   R  road                   W  sidewalk / footpath  D  dirt trail
//   p  parking lot   r b y g u o k  parking lots by permit color (red, blue,
//                  yellow, green, purple, orange, black)
//   F  field / turf           ~  water                =  bridge
//   Y  football field         S  stadium bleachers (impassable)
//   H  pillar of the Transformational Link arch
//   G  golf course            A  farmland             K  Cook Carillon Tower
//   T  woods (dense trees)    t  garden (trees)       V  ravine (impassable)
//
// Rerunning the converter overwrites hand edits, so keep a copy of anything
// you change, or make the change in the converter instead.
"""


def to_xy(lat, lon):
    """Degrees -> tile coordinates (floating point)."""
    return ((lon - WEST) * M_PER_DEG_LON / TILE_M, (NORTH - lat) * M_PER_DEG_LAT / TILE_M)


def load(path):
    root = ET.parse(path).getroot()
    nodes = {n.get('id'): (float(n.get('lat')), float(n.get('lon'))) for n in root.iter('node')}
    node_tags = {n.get('id'): {t.get('k'): t.get('v') for t in n.findall('tag')} for n in root.iter('node') if n.find('tag') is not None}
    ways = {}
    for w in root.iter('way'):
        pts = [nodes[nd.get('ref')] for nd in w.findall('nd') if nd.get('ref') in nodes]
        ways[w.get('id')] = {'tags': {t.get('k'): t.get('v') for t in w.findall('tag')}, 'pts': pts}
    rels = []
    for r in root.iter('relation'):
        members = [(m.get('type'), m.get('ref'), m.get('role')) for m in r.findall('member')]
        rels.append({'tags': {t.get('k'): t.get('v') for t in r.findall('tag')}, 'members': members})
    return nodes, node_tags, ways, rels


def join_rings(segments):
    """Join open way segments that share endpoints into closed rings."""
    segs = [list(s) for s in segments if len(s) >= 2]
    rings = []
    while segs:
        ring = segs.pop(0)
        changed = True
        while ring[0] != ring[-1] and changed:
            changed = False
            for i, s in enumerate(segs):
                if s[0] == ring[-1]:
                    ring += s[1:]
                elif s[-1] == ring[-1]:
                    ring += s[::-1][1:]
                elif s[-1] == ring[0]:
                    ring = s + ring[1:]
                elif s[0] == ring[0]:
                    ring = s[::-1] + ring[1:]
                else:
                    continue
                segs.pop(i)
                changed = True
                break
        rings.append(ring)
    return rings


def areas(ways, rels):
    """Yield (tags, [outer rings], [inner rings]) for every area."""
    for w in ways.values():
        p = w['pts']
        if len(p) >= 4 and p[0] == p[-1]:
            yield w['tags'], [p], []
    for r in rels:
        if r['tags'].get('type') not in ('multipolygon', None) and 'building' not in r['tags']:
            continue
        outer = [ways[ref]['pts'] for t, ref, role in r['members'] if t == 'way' and ref in ways and role != 'inner']
        inner = [ways[ref]['pts'] for t, ref, role in r['members'] if t == 'way' and ref in ways and role == 'inner']
        if outer:
            yield r['tags'], join_rings(outer), join_rings(inner)


class Raster:
    """Tile grid of characters plus supersampled polygon drawing."""

    def __init__(self):
        self.grid = [['.'] * W for _ in range(H)]

    def fill_area(self, outers, inners, ch, threshold=0.5, only=None):
        """Fill tiles covered at least `threshold` by the polygon; return them."""
        rings_o = [[to_xy(*p) for p in r] for r in outers if len(r) >= 3]
        rings_i = [[to_xy(*p) for p in r] for r in inners if len(r) >= 3]
        if not rings_o:
            return []
        xs = [x for r in rings_o for x, _ in r]
        ys = [y for r in rings_o for _, y in r]
        x0, y0 = max(0, int(min(xs))), max(0, int(min(ys)))
        x1, y1 = min(W, int(max(xs)) + 1), min(H, int(max(ys)) + 1)
        if x0 >= x1 or y0 >= y1:
            return []
        img = Image.new('L', ((x1 - x0) * SUPER, (y1 - y0) * SUPER), 0)
        d = ImageDraw.Draw(img)
        for r, fill in [(r, 255) for r in rings_o] + [(r, 0) for r in rings_i]:
            d.polygon([((x - x0) * SUPER, (y - y0) * SUPER) for x, y in r], fill=fill)
        cov = img.resize((x1 - x0, y1 - y0), Image.BOX).load()
        cells = []
        for y in range(y0, y1):
            for x in range(x0, x1):
                if cov[x - x0, y - y0] >= threshold * 255 and (only is None or self.grid[y][x] in only):
                    self.grid[y][x] = ch
                    cells.append((x, y))
        return cells

    def line(self, pts, ch, width, only=None):
        """Draw a polyline `width` tiles wide. Thin lines are kept 4-connected
        (no diagonal-only steps) so they can always be walked along."""
        r = max(0.5, width / 2)

        def put(tx, ty):
            if 0 <= tx < W and 0 <= ty < H and (only is None or self.grid[ty][tx] in only):
                self.grid[ty][tx] = ch

        last = None
        for a, b in zip(pts, pts[1:]):
            (ax, ay), (bx, by) = to_xy(*a), to_xy(*b)
            n = max(1, int(math.hypot(bx - ax, by - ay) * 3))
            for i in range(n + 1):
                x = ax + (bx - ax) * i / n
                y = ay + (by - ay) * i / n
                for ty in range(int(y - r), int(y + r) + 1):
                    for tx in range(int(x - r), int(x + r) + 1):
                        if (tx + 0.5 - x) ** 2 + (ty + 0.5 - y) ** 2 <= r * r + 0.05:
                            put(tx, ty)
                cur = (int(x), int(y))
                if last and abs(cur[0] - last[0]) == 1 and abs(cur[1] - last[1]) == 1:
                    put(last[0], cur[1])   # fill the corner of a diagonal step
                last = cur


ROAD_WIDTH_M = {
    'motorway': 26, 'trunk': 24, 'primary': 20, 'secondary': 16, 'tertiary': 14,
    'unclassified': 12, 'residential': 12, 'trunk_link': 10, 'secondary_link': 10,
    'tertiary_link': 10, 'service': 8, 'living_street': 10,
}
FOOT = {'footway', 'path', 'cycleway', 'pedestrian', 'steps', 'corridor', 'bridleway'}


def building_style(t):
    b = t.get('building', 'yes')
    if b in ('house', 'detached', 'semidetached_house', 'residential', 'garage', 'shed', 'bungalow'):
        return 'house'
    if b in ('commercial', 'retail', 'supermarket') or t.get('shop') or t.get('amenity') in ('fast_food', 'restaurant', 'cafe', 'pub', 'bank', 'fuel'):
        return 'shop'
    if b == 'church' or t.get('amenity') == 'place_of_worship':
        return 'stone'
    return None   # use the game's default for campus buildings


def inside(pt, ring):
    """Is (lat, lon) inside the polygon ring?"""
    y, x = pt
    hit = False
    for (y1, x1), (y2, x2) in zip(ring, ring[1:] + ring[:1]):
        if (y1 > y) != (y2 > y) and x < x1 + (y - y1) * (x2 - x1) / (y2 - y1):
            hit = not hit
    return hit


def slug(name):
    s = re.sub(r'[^a-z0-9]+', '_', name.lower()).strip('_')
    return s[:24] or 'building'


def main():
    src = sys.argv[1]
    image = sys.argv[sys.argv.index('--campus-image') + 1] if '--campus-image' in sys.argv else None
    preview = sys.argv[sys.argv.index('--preview') + 1] if '--preview' in sys.argv else None
    nodes, node_tags, ways, rels = load(src)
    R = Raster()
    all_areas = list(areas(ways, rels))

    def has(t, k, *vals):
        return k in t and (not vals or t[k] in vals)

    # 1. Land cover, broadest first.
    for t, outers, inners in all_areas:
        if has(t, 'landuse', 'farmland', 'farmyard', 'orchard'):
            R.fill_area(outers, inners, 'A')
    for t, outers, inners in all_areas:
        if has(t, 'leisure', 'golf_course'):
            R.fill_area(outers, inners, 'G')
    for t, outers, inners in all_areas:
        if has(t, 'natural', 'wood', 'scrub', 'wetland') or has(t, 'landuse', 'forest'):
            R.fill_area(outers, inners, 'T')
    for t, outers, inners in all_areas:
        if has(t, 'leisure', 'garden'):
            R.fill_area(outers, inners, 't')
    for t, outers, inners in all_areas:
        if has(t, 'leisure', 'stadium') and not has(t, 'building'):
            R.fill_area(outers, inners, 'W')   # concourse; field and stands go on top
    for t, outers, inners in all_areas:
        if has(t, 'leisure', 'pitch', 'track') and not has(t, 'building'):
            R.fill_area(outers, inners, 'F')

    # 2. Water areas and streams.
    for t, outers, inners in all_areas:
        if has(t, 'natural', 'water') or has(t, 'water') or has(t, 'waterway', 'riverbank') or has(t, 'leisure', 'swimming_pool') and not has(t, 'indoor'):
            if has(t, 'leisure', 'swimming_pool'):
                continue   # pools are mostly indoors / tiny
            R.fill_area(outers, inners, '~', threshold=0.45)
    for w in ways.values():
        t = w['tags']
        if has(t, 'waterway', 'stream', 'river', 'drain', 'ditch', 'canal') and not has(t, 'tunnel', 'culvert', 'yes'):
            R.line(w['pts'], '~', 1.0 if t['waterway'] != 'river' else 3.0)

    # 3. Parking lots.
    lots = []
    for t, outers, inners in all_areas:
        if has(t, 'amenity', 'parking') and not has(t, 'parking', 'underground', 'multi-storey'):
            cells = R.fill_area(outers, inners, 'p', threshold=0.45)
            if cells:
                lots.append(cells)

    # 4. Footpaths, then roads on top, then bridges.
    for w in ways.values():
        t = w['tags']
        if t.get('highway') in FOOT and not has(t, 'indoor', 'yes') and not has(t, 'tunnel', 'yes', 'building_passage'):
            R.line(w['pts'], 'W', 1.0, only=set('.ATtFG'))
        elif t.get('highway') == 'track':
            R.line(w['pts'], 'D', 1.0, only=set('.ATtFG'))
    for w in ways.values():
        t = w['tags']
        width = ROAD_WIDTH_M.get(t.get('highway'))
        if has(t, 'service', 'parking_aisle', 'drive-through'):
            continue   # aisles inside lots: the lot is drawn already
        if width and not has(t, 'tunnel', 'yes'):
            R.line(w['pts'], 'R', max(1.0, width / TILE_M))
    for w in ways.values():
        t = w['tags']
        if has(t, 'bridge') and t.get('bridge') != 'no' and t.get('highway') in FOOT:
            R.line(w['pts'], '=', 1.0, only=set('~TV.WGtD'))

    # 5. Buildings.
    buildings = []
    carillon = None
    for t, outers, inners in all_areas:
        if not has(t, 'building') or t.get('building') in ('roof', 'no', 'construction'):
            continue
        name = t.get('name', '')
        if 'Carillon' in name:
            xs = [to_xy(*p)[0] for ring in outers for p in ring]
            ys = [to_xy(*p)[1] for ring in outers for p in ring]
            carillon = (int(sum(xs) / len(xs)), int(sum(ys) / len(ys)))
            continue
        cells = R.fill_area(outers, inners, 'B', threshold=0.4)
        if not cells:
            # Small buildings still get one tile at their center.
            xs = [to_xy(*p)[0] for ring in outers for p in ring]
            ys = [to_xy(*p)[1] for ring in outers for p in ring]
            cx, cy = int(sum(xs) / len(xs)), int(sum(ys) / len(ys))
            if 0 <= cx < W and 0 <= cy < H:
                R.grid[cy][cx] = 'B'
                cells = [(cx, cy)]
            else:
                continue
        xs = [to_xy(*p)[0] for ring in outers for p in ring]
        ys = [to_xy(*p)[1] for ring in outers for p in ring]
        center = (sum(xs) / len(xs), sum(ys) / len(ys))
        at = min(cells, key=lambda c: (c[0] + 0.5 - center[0]) ** 2 + (c[1] + 0.5 - center[1]) ** 2)
        bid = next((gid for pat, gid in GAME_IDS if re.search(pat, name)), None)
        style = building_style(t)
        if not name:
            name = {'house': 'A house', 'shop': 'A shop'}.get(style, 'Campus building')
        buildings.append({'id': bid or slug(name), 'name': name, 'style': style, 'at': at, 'center': center, 'tags': t})

    # Football stadiums: the field gets yard lines, and bleachers go along
    # both long sides.
    for t, outers, inners in all_areas:
        if not (has(t, 'leisure', 'pitch') and 'american_football' in t.get('sport', '')):
            continue
        field = R.fill_area(outers, inners, 'Y', threshold=0.5, only=set('F.W'))
        if not field:
            continue
        stadium = any(has(t2, 'leisure', 'stadium') and inside(outers[0][0], o2[0])
                      for t2, o2, _ in all_areas if o2)
        if not stadium:
            continue
        # Square the field up so yard lines and end zones line up.
        fx0, fx1 = min(x for x, _ in field), max(x for x, _ in field)
        fy0, fy1 = min(y for _, y in field), max(y for _, y in field)
        for y in range(fy0, fy1 + 1):
            for x in range(fx0, fx1 + 1):
                R.grid[y][x] = 'Y'
        rows = {y: (fx0, fx1) for y in range(fy0, fy1 + 1)}
        for y, (lo, hi) in rows.items():
            for x in list(range(lo - STAND_DEPTH, lo)) + list(range(hi + 1, hi + 1 + STAND_DEPTH)):
                if 0 <= x < W and R.grid[y][x] in '.RWFTG':
                    R.grid[y][x] = 'S'

    # The Transformational Link arch (tagged "Transitional Link" in OSM): two
    # pillars with the walkway passing between them.
    arch = None
    for t, outers, inners in all_areas:
        if has(t, 'tourism', 'artwork') and 'Link' in t.get('name', ''):
            xs = [to_xy(*p)[0] for ring in outers for p in ring]
            ys = [to_xy(*p)[1] for ring in outers for p in ring]
            ax, ay = int(sum(xs) / len(xs)), int(sum(ys) / len(ys))
            for y in range(ay - 2, ay + 3):
                for x in range(ax - 2, ax + 3):
                    if R.grid[y][x] in '.TtB':
                        R.grid[y][x] = 'W'
            R.grid[ay][ax - 1] = R.grid[ay][ax + 1] = 'H'
            arch = [ax, ay]

    # Cook Carillon Tower: a 2x2 landmark with open ground around it.
    if carillon:
        cx, cy = carillon[0] - 1, carillon[1] - 1
        for y in range(cy - 2, cy + 4):
            for x in range(cx - 2, cx + 4):
                if 0 <= x < W and 0 <= y < H and R.grid[y][x] in 'B.':
                    R.grid[y][x] = 'W'
        for y in range(cy, cy + 2):
            for x in range(cx, cx + 2):
                R.grid[y][x] = 'K'
        carillon = [cx, cy]
    # Buildings whose `at` tile got overwritten (e.g. by the carillon plaza).
    buildings = [b for b in buildings if R.grid[b['at'][1]][b['at'][0]] == 'B']

    # Keep ids unique.
    seen = {}
    for b in buildings:
        n = seen.get(b['id'], 0)
        seen[b['id']] = n + 1
        if n:
            b['id'] = '%s_%d' % (b['id'], n + 1)

    # 6. Line the campus map image up with the tiles (affine fit), and use it
    #    for parking permit colors.
    affine = None
    if image:
        pairs = []
        for key, ix, iy in IMAGE_LABELS:
            m = [b for b in buildings if key.lower() in b['name'].lower()]
            if m:
                pairs.append(((ix, iy), m[0]['center']))
        affine = fit_affine(pairs)
        err = [math.hypot(*(a - b for a, b in zip(apply_affine(affine, p), q))) for p, q in pairs]
        print('aligned campus map image with %d buildings, mean error %.1f tiles' % (len(pairs), sum(err) / len(err)))
        color_lots(R, lots, image, affine)

    write(R, buildings, carillon, affine, arch)
    if preview:
        save_preview(R, preview)


def fit_affine(pairs):
    """Least-squares affine (image px -> tile): returns [a, b, c, d, e, f]."""
    import numpy as np
    A = np.array([[x, y, 1] for (x, y), _ in pairs], dtype=float)
    tx = np.array([q[0] for _, q in pairs])
    ty = np.array([q[1] for _, q in pairs])
    a = np.linalg.lstsq(A, tx, rcond=None)[0]
    d = np.linalg.lstsq(A, ty, rcond=None)[0]
    return [round(float(v), 6) for v in list(a) + list(d)]


def apply_affine(m, p):
    x, y = p
    return (m[0] * x + m[1] * y + m[2], m[3] * x + m[4] * y + m[5])


def color_lots(R, lots, image, affine):
    """Give each lot the permit color found at the same spot on the campus map."""
    import numpy as np
    im = np.array(Image.open(image).convert('RGB')).astype(int)
    a, b, c, d, e, f = affine
    inv = np.linalg.inv(np.array([[a, b], [d, e]]))
    permit = {
        'r': lambda r, g, bb: r > 170 and g < 120 and bb < 130,
        'b': lambda r, g, bb: bb > 150 and r < 90 and g < 190,
        'y': lambda r, g, bb: r > 190 and g > 150 and bb < 90,
        'g': lambda r, g, bb: g > 130 and r < 140 and bb < 130 and g - r > 40,
        'u': lambda r, g, bb: bb > 110 and g < 80 and r < 140,
        'o': lambda r, g, bb: r > 210 and 80 < g < 170 and bb < 80,
        'k': lambda r, g, bb: max(r, g, bb) < 42,
    }
    for cells in lots:
        votes = {}
        for tx, ty in cells:
            ix, iy = inv @ np.array([tx + 0.5 - c, ty + 0.5 - f])
            ix, iy = int(round(ix)), int(round(iy))
            if not (0 <= iy < im.shape[0] and 145 <= ix < 538):
                continue
            px = tuple(im[iy, ix])
            for ch, test in permit.items():
                if test(*px):
                    votes[ch] = votes.get(ch, 0) + 1
        if votes and max(votes.values()) >= max(2, len(cells) // 6):
            ch = max(votes, key=votes.get)
            for tx, ty in cells:
                if R.grid[ty][tx] == 'p':
                    R.grid[ty][tx] = ch


def write(R, buildings, carillon, affine, arch):
    dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'campus_map.js')
    rows = [''.join(r) for r in R.grid]
    with open(dst, 'w') as f:
        f.write(HEADER)
        f.write('window.LQ = window.LQ || {};\n\n')
        f.write('LQ.CAMPUS_MAP = {\n')
        f.write('  width: %d,\n  height: %d,\n' % (W, H))
        f.write('  // Each tile is %g meters. Tile (0, 0) is the northwest corner, at\n' % TILE_M)
        f.write('  // latitude %.4f, longitude %.4f.\n' % (NORTH, WEST))
        f.write('  tileMeters: %g,\n  north: %.4f,\n  west: %.4f,\n' % (TILE_M, NORTH, WEST))
        f.write('  // Converts GVSU campus map image pixels (x, y) to tiles:\n')
        f.write('  //   tileX = a*x + b*y + c,  tileY = d*x + e*y + f\n')
        f.write('  imgAffine: %s,\n' % json.dumps(affine))
        f.write('  // Top-left tile of the 2x2 Cook Carillon Tower.\n')
        f.write('  carillon: %s,\n' % json.dumps(carillon))
        f.write('  // Center tile of the Transformational Link arch (pillars are the H tiles beside it).\n')
        f.write('  arch: %s,\n\n' % json.dumps(arch))
        f.write('  // One string per row of tiles, north to south. Row numbers are in the comments.\n')
        f.write('  rows: [\n')
        for ty, row in enumerate(rows):
            f.write("    '%s', // %d\n" % (row, ty))
        f.write('  ],\n\n')
        f.write('  // Building names. `at` is any tile inside the building (x, y). `style`\n')
        f.write('  // picks the look (house, shop, stone, ...). Buildings not listed here are\n')
        f.write('  // still built from their B tiles, just unnamed.\n')
        f.write('  buildings: [\n')
        for b in sorted(buildings, key=lambda b: (b['at'][1], b['at'][0])):
            extra = ', style: %s' % json.dumps(b['style']) if b['style'] else ''
            f.write('    { id: %s, name: %s, at: [%d, %d]%s },\n' % (
                json.dumps(b['id']), json.dumps(b['name']), b['at'][0], b['at'][1], extra))
        f.write('  ],\n};\n')
    named = sum(1 for b in buildings if b['name'] not in ('A house', 'A shop', 'Campus building'))
    print('wrote %s: %d x %d tiles, %d buildings (%d named)' % (os.path.normpath(dst), W, H, len(buildings), named))


def save_preview(R, path):
    pal = {'.': (120, 192, 96), 'B': (40, 50, 70), 'R': (90, 90, 100), 'W': (225, 220, 200),
           'p': (140, 140, 150), 'r': (220, 60, 60), 'b': (40, 120, 210), 'y': (230, 190, 30), 'g': (40, 170, 70),
           'H': (240, 240, 250), 'Y': (40, 140, 60), 'S': (150, 150, 170), 'u': (100, 50, 150), 'o': (240, 130, 40), 'k': (20, 20, 20), 'F': (60, 160, 60), '~': (70, 150, 230),
           'G': (150, 215, 130), 'A': (160, 120, 72), 'T': (30, 90, 40), 'V': (40, 80, 40), 'D': (200, 160, 112),
           '=': (180, 140, 90), 't': (80, 140, 70), 'K': (250, 210, 60)}
    img = Image.new('RGB', (W, H))
    for y, row in enumerate(R.grid):
        for x, ch in enumerate(row):
            img.putpixel((x, y), pal.get(ch, (255, 0, 255)))
    img.resize((W * 2, H * 2), Image.NEAREST).save(path)


if __name__ == '__main__':
    main()
